#nacos:
#  config:
#    bootstrap:
#      enable: true
#    server-addr: your-server-addr
#    # 主配置 data-id
#    data-id: your-data-id
#    # 命名空间ID
#    namespace: namespace
#    # 主配置 group-id
#    group: DEFAULT_GROUP
#    # 主配置 配置文件类型
#    type: yaml
#    # 主配置 最大重试次数
#    max-retry: 10
#    # 主配置 开启自动刷新
#    auto-refresh: true
#    # 主配置 重试时间
#    config-retry-time: 2000
#    # 主配置 配置监听长轮询超时时间
#    config-long-poll-timeout: 20000
#    # 主配置 开启注册监听器预加载配置服务（除非特殊业务需求，否则不推荐打开该参数）
#    enable-remote-sync-config: false
#    # 允许nacos上的配置优先于本地配置
#    remote-first: true

#logging:
#  level:
#    root: debug
server:
  port: 18081
  servlet:
    context-path: /kai/
logging:
  level:
    root: info
spring:
  #es配置
  data:
    redis:
      host: your-host
      port: 16384
      password: your-password
      timeout: 5000
      connect-timeout: 5000
    elasticsearch:
      # elasticsearch:
      rest:
        #最新配置方式使用restful风格，端口从9300 -> 9200
        #      uris: 127.0.0.1:9200
        uris: 172.21.0.51:9200
        username: elastic
        password: elastic
  datasource:
    url: jdbc:mysql://your-mysql/new_exam?useUnicode=true&characterEncoding=utf-8
    username: your-username
    password: your-password
    druid:
      #2.连接池配置
      #初始化连接池的连接数量 大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 5000
      #3.基础监控配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        #设置不统计哪些URL
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 100
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        #设置监控页面的登录名和密码
        login-username: admin
        login-password: admin
        allow: 127.0.0.1
        #deny: 192.168.1.100
  sql:
    init:
      encoding: utf-8
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.login.user_login.mapper
  # configuration:
  #   map-underscore-to-camel-case: true
  #   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      select-strategy: not_empty
